{
 "title": "Zabbix - Monitoramento Sefaz",
 "description": "The URL for the Zabbix Template was updated",
 "tags": [ "sefaz" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Sefaz", "query": "*.Sefaz.*.*" },
   { "name": "Services", "query": "*.Sefaz.*.*" },
   { "name": "Estados", "query": "*.Sefaz.*.*" }
  ]
 },
 "panels": [
  {
   "title": "$Estados",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 1.7142857142857142, "x": 0, "y": 0 },
   "repeat": "Estados",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Sefaz" },
     "item": {
      "filter": "Failed step of scenario \"$Estados\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Brazil",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 21, "w": 9, "x": 0, "y": 2 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Sefaz" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/.*Failed step of scenario \"([^.]*)\".*/",
        "$1"
       ],
       "text": "replaceAlias(/.*Failed step of scenario \"([^.]*)\".*/, $1)"
      }
     ],
     "host": { "filter": "Sefaz" },
     "item": {
      "filter": "Failed step of scenario \"$Estados\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "select * \nfrom httptest_field ",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 2 },
   "repeat": "Services",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Sefaz" },
     "item": {
      "filter": "Response code for step \"$Services\" of scenario \"$Sefaz\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "repeat": "Services",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Sefaz" },
     "item": {
      "filter": "Response time for step \"$Services\" of scenario \"$Sefaz\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Services",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "repeat": "Services",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "Sefaz" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "Sefaz" },
     "item": {
      "filter": "Response time for step \"$Services\" of scenario \"$Sefaz\"."
     },
     "itemids": "$Sefaz",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 23 },
   "content": "UF que utilizam a <b>SVAN</b>- Sefaz Virtual do Ambiente Nacional: <b>MA, PA</b><br>\r\nUF que utilizam a <b>SVRS</b> - Sefaz Virtual do <b>RS:</b><br>\r\n<li>Para serviço de Consulta Cadastro: <b>AC, RN, PB, SC</b>\r\n<li>Para demais serviços relacionados com o sistema da NF-e: <b>AC, AL, AP, DF, ES, PB, PI, RJ, RN, RO, RR, SC, SE, TO</b><br>\r\n<br>\r\nAutorizadores em contingência: \r\n<li>UF que utilizam a <b>SVC-AN</b> - Sefaz Virtual de Contingência Ambiente Nacional: <b>AC, AL, AP, DF, ES, MG, PB, PI, RJ, RN, RO, RR, RS, SC, SE, SP, TO</b>\r\n<li>UF que utilizam a <b>SVC-RS</b> - Sefaz Virtual de Contingência Rio Grande do Sul: <b>AM, BA, CE, GO, MA, MS, MT, PA, PE, PR</b>"
  }
 ]
}